include: package:solid_lints/analysis_options.yaml

custom_lint:
  rules:
    - newline_before_return: false

linter:
  rules:
    avoid_print: false
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
